services:
  catalogDb:
    container_name: catalogDb
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: catalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
        - postgres_catalog:/var/lib/postgresql/data
    image: postgres
#  catalog.api:
#    image: catalog.api
#    build:
#      context: .
#      dockerfile: Services/Catalog/Catalog.API/Dockerfile
volumes:
  postgres_catalog:
    
